export const SET_NAME = "SET_NAME";
export const SET_AGE = "SET_AGE";
export const SET_PREV_EMPLOYER_1_NAME = "SET_PREV_EMPLOYER_1_NAME";
export const SET_PREV_EMPLOYER_1_DURATION = "SET_PREV_EMPLOYER_1_DURATION";
export const SET_PREV_EMPLOYER_2_NAME = "SET_PREV_EMPLOYER_2_NAME";
export const SET_PREV_EMPLOYER_2_DURATION = "SET_PREV_EMPLOYER_2_DURATION";
export const SET_PREV_EMPLOYER_3_NAME = "SET_PREV_EMPLOYER_3_NAME";
export const SET_PREV_EMPLOYER_3_DURATION = "SET_PREV_EMPLOYER_3_DURATION";
